# =========================================================
# APPLICATION
# =========================================================

spring.application.name=LeadPilot-CRM


# =========================================================
# SERVER
# =========================================================

# Render provides PORT.
# Locally, it will use 8080.

server.port=${PORT:8080}


# =========================================================
# MYSQL DATABASE
# =========================================================

# LOCAL:
# jdbc:mysql://localhost:3306/leadpilot_crm
#
# RENDER:
# DATABASE_URL environment variable will be used.

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/leadpilot_crm}

spring.datasource.username=${DATABASE_USERNAME:root}

# IMPORTANT:
# Replace YOUR_LOCAL_MYSQL_PASSWORD with your current
# local MySQL password.
#
# On Render, DATABASE_PASSWORD will override this value.

spring.datasource.password=${DATABASE_PASSWORD:Soumya@2026work}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# SWAGGER
# =========================================================

springdoc.swagger-ui.path=/swagger-ui.html


# =========================================================
# JACKSON
# =========================================================

spring.jackson.date-format=dd-MM-yyyy HH:mm:ss

spring.jackson.time-zone=Asia/Kolkata


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=5MB

spring.servlet.multipart.max-request-size=5MB


# =========================================================
# LOGGING
# =========================================================

logging.level.org.hibernate.SQL=INFO

logging.level.org.hibernate.orm.jdbc.bind=INFO


# =========================================================
# JWT
# =========================================================

# LOCAL:
# The value after : is used.
#
# RENDER:
# JWT_SECRET environment variable is used.

jwt.secret=${JWT_SECRET:s8rCBEPAlp36JuAr//HcUXxqZPJp7oi9miotOgWzQKYOsIBaocW7G02L+7F/sJvZsghSEjYybaCWSPLL2jbSxQ==}

jwt.expiration=${JWT_EXPIRATION:86400000}