package com.leadpilot.crm.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.leadpilot.crm.dto.AdminDashboardResponse;
import com.leadpilot.crm.dto.ExecutiveDashboardResponse;
import com.leadpilot.crm.service.DashboardService;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

/**
 * ==========================================================
 * Controller : DashboardController
 *
 * Description :
 * Provides APIs for retrieving CRM dashboard information.
 *
 * Supported dashboards:
 *
 * - Admin Dashboard
 * - Executive Dashboard
 *
 * The dashboard data is generated by DashboardService and
 * returned through dedicated dashboard response DTOs.
 *
 * ==========================================================
 */
@RestController
@RequestMapping("/api/dashboard")
@SecurityRequirement(name = "bearerAuth")
@Tag(
        name = "Dashboard",
        description = "APIs for Admin and Executive CRM dashboards"
)
public class DashboardController {

    // ==========================================================
    // Service
    // ==========================================================

    private final DashboardService dashboardService;

    // ==========================================================
    // Constructor Injection
    // ==========================================================

    public DashboardController(
            DashboardService dashboardService) {

        this.dashboardService = dashboardService;
    }

    // ==========================================================
    // ADMIN DASHBOARD
    // ==========================================================

    /**
     * Retrieves the complete Admin Dashboard.
     *
     * The Admin Dashboard contains organization-wide
     * CRM information including:
     *
     * - Dashboard summary
     * - Lead status chart
     * - Lead priority chart
     * - Lead source chart
     * - Monthly lead chart
     * - Recent leads
     * - Today's follow-ups
     * - Recent notes
     * - Upcoming visits
     * - Overdue follow-ups
     *
     * @param userId ID of the logged-in Admin
     * @return complete Admin Dashboard response
     */
    @Operation(
            summary = "Get Admin Dashboard",
            description = "Retrieves the complete organization-wide dashboard for an Admin user, including lead statistics, charts, recent leads, follow-ups, notes, visits, and overdue follow-ups."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Admin dashboard retrieved successfully"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Admin user not found"
            ),
            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error"
            )
    })
    @GetMapping("/admin/{userId}")
    public ResponseEntity<AdminDashboardResponse> getAdminDashboard(

            @Parameter(
                    description = "Unique ID of the Admin user",
                    required = true,
                    example = "1"
            )
            @PathVariable Long userId) {

        AdminDashboardResponse response =
                dashboardService.getAdminDashboard(userId);

        return ResponseEntity.ok(response);
    }

    // ==========================================================
    // EXECUTIVE DASHBOARD
    // ==========================================================

    /**
     * Retrieves the complete Executive Dashboard.
     *
     * The Executive Dashboard contains only information
     * belonging to the requested executive.
     *
     * It includes:
     *
     * - Dashboard summary
     * - Lead status chart
     * - Lead priority chart
     * - Lead source chart
     * - Monthly lead chart
     * - Recent leads
     * - Today's follow-ups
     * - Recent notes
     * - Upcoming visits
     * - Overdue follow-ups
     *
     * @param userId ID of the logged-in Executive
     * @return complete Executive Dashboard response
     */
    @Operation(
            summary = "Get Executive Dashboard",
            description = "Retrieves the complete dashboard for an Executive user. Dashboard information is restricted to leads, follow-ups, notes, visits, and activities associated with that executive."
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Executive dashboard retrieved successfully"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Executive user not found"
            ),
            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error"
            )
    })
    @GetMapping("/executive/{userId}")
    public ResponseEntity<ExecutiveDashboardResponse> getExecutiveDashboard(

            @Parameter(
                    description = "Unique ID of the Executive user",
                    required = true,
                    example = "2"
            )
            @PathVariable Long userId) {

        ExecutiveDashboardResponse response =
                dashboardService.getExecutiveDashboard(userId);

        return ResponseEntity.ok(response);
    }
}